spring.application.name=travel
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=travel_3;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=file:///C:/images/

jwt.secret=mySuperSecretKey12345678901234567890123456789012

#----------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587    
# spring.mail.username=ketdvpc06920@fpt.edu.vn
# spring.mail.password=idqq tpjr fola uihw
spring.mail.username=dinhvanket36@gmail.com
spring.mail.password=bxfp awcy cjwo extm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.facebook.client-id=8467059656742501
spring.security.oauth2.client.registration.facebook.client-secret=8e47508bf9d844388c51a5c5369a71ec

PAYOS_CLIENT_ID=b3777a23-4f92-4a96-b128-2001be88c839
PAYOS_API_KEY=624741fb-23dc-487b-bc53-b56ba90e4272
PAYOS_CHECKSUM_KEY=1848ce3521724a3f1bb5d3f825644cf366d83c3458dc7efcc3dab2eb7d81659d




#logging.level.org.hibernate.SQL=OFF
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

