spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1030168414764-o0eta5kp7iu1r2t2mod0ce35asmh9re7.apps.googleusercontent.com
            client-secret: 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
server:
  port: 8080
